### Aula 03
Introdução a aula 03
---
- Biblioteca Pandas
- Biblioteca Numpy
---
```python
print("Olá mundo")
```
1. Conhecendo a biblioteca
2. Executando comandos

In [ ]:
import pandas as pd
import numpy as np

In [5]:
quantidade_produtos = [3,5,6,10]
preco_produtos = [10,5,7,100]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(preco_produtos)

faturamento = array_produtos * array_precos
print(faturamento)

[  30   25   42 1000]

In [8]:
quantidade_produtos = [3,5,6,10]
preco_produtos = [10,5,7,100]
nomes_produtos = ["Caçulinha","Pastel","Refrigerante","Combos"]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(preco_produtos)

faturamento = array_produtos * array_precos


for nome,preco in zip(nomes_produtos,faturamento):
    print(f"{nome} : {preco}")

Caçulinha : 30
Pastel : 25
Refrigerante : 42
Combos : 1000

#

### Exercício de fixação 
- Criar uma lista que irá possuir 10 nomes de produtos.
- Criar uma lista que irá possuir o preço de custo (atacado).
- Criar uma lista que irá possuir o preço de venda (varejo).
- Ao final, exibir o lucro obtido em cada produto.

In [13]:
#Lista de nomes
produtos = ["Celular","Televisão","Notebook","Computador","Teclado"]
#Lista de preços atacado
preco_atacado = [2000,3000,4500,5000,100]
#Lista de preços varejo
preco_varejo = [2500,4000,5000,7000,120]
#Array
array_atacado = np.array(preco_atacado)
array_varejo = np.array(preco_varejo)

lucro = array_varejo - array_atacado
lucro_obtido = np.sum(lucro)
print(f"O lucro obtido foi R${lucro_obtido}")

for nome,lucro_produto in zip(produtos,lucro):
    print(f"O lucro do produto {nome} foi {lucro_produto}")

O lucro obtido foi R$4020
O lucro do produto Celular foi 500
O lucro do produto Televisão foi 1000
O lucro do produto Notebook foi 500
O lucro do produto Computador foi 2000
O lucro do produto Teclado foi 20

# Pandas

In [20]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head() #Por padrão, ele exibe as 5 primeiras informações

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [23]:
df.tail() #Exibe as 5 últimas

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [25]:
#Dimensões da tabela
df.shape

(40, 6)

In [ ]:
#Exibe as colunas da base de dados
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [ ]:
#Contar valores duplicados
df.duplicated().sum()

np.int64(0)

In [ ]:
#Contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [30]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000